services:
  server:
    build: .
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - mongo
    env_file: ".env"

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo-volume:/data/db
      - mongo-volume:/data/configdb
    env_file: ".env.db"

volumes:
  mongo-volume:
