services:
  server:
    build: .
    restart: always
    ports:
      - 443:443
    depends_on:
      - mongo
    env_file: ".env"

  mongo:
    image: mongo
    restart: always
    ports:
      # Expose on host port 27018 (Not needed in production)
      - 27018:27017
    volumes:
      - mongo-volume:/data/db
      - mongo-volume:/data/configdb
    env_file: ".env.db"

volumes:
  mongo-volume:
