name: Deploy App

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4
        with:
          sparse-checkout: "frontend"
          sparse-checkout-cone-mode: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.8.x"
      - run: cd ./frontend
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist
